name: Enterprise Apps
favicon: null
layout_spectrum: 0.98986
typography_spectrum: 0.74507
title: 'Winning Application Strategies for Enterprises '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#484848'
    - '#8fc086'
    - '#8889c0'
    - '#e2855a'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
