name: Enterprise Apps
favicon: null
layout_spectrum: 0.4783360620494932
typography_spectrum: 0.7466263109818101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9844678067602217
  lightness: 0.3654901592526585
  saturation: 0.6634099108632654
  rhythmicContrast: 0.5265383815858513
purpose: []
