name: Enterprise Apps
favicon: null
layout_spectrum: 0.25196
typography_spectrum: 0.74507
title: 'Winning Application Strategies for Enterprises '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#484848'
    - '#8fc086'
    - '#8889c0'
    - '#e2855a'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
