name: Enterprise Apps
favicon: null
layout_spectrum: 0.4783360620494932
typography_spectrum: 0.7466263109818101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf8ef'
    - '#b21e13'
    - '#6c0101'
    - '#dec9aa'
    - '#b48264'
  brandStrength: 0.875
  lightness: 0.3654901592526585
  saturation: 0.6634099108632654
  rhythmicContrast: 0.5265383815858513
purpose: []
